### ISSUE TITLE
Deep-link message notifications to the received message

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#223]
Use the message ID in the payload to route directly to the message. As we won't have performed a fetch in the background, a model refresh will need to be performed on entering the foreground followed by:

- Showing an alert if the download failed (we won't be able to route to a record we don't hold locally)
- Pushing the message detail module into sight configured with the new record

**Tasks**

- [x] Add API to `PrivateMessagesService` that returns a `Message` by its identifier
- [x] Adjust `MessageDetailModuleProviding` to accept an ID (using the service)
- [x] Add capability for `NotificationResponseProcessor` to handle messages by their ID and open via the content recipient
- [x] Make opening messages by their ID 'public' on the director
- [x] Select news tab when opening message

**Comment by ShezHsky** [comment]
Incoming notification responses relating to a message contain a `message_id` key, where the value is a String containing the identifier of the message. As with other notification handling routes the app should:

- Sync/load messages to download a copy
- On success, pass the message to the content router
- On failure, do nothing - the app opening is existing (good enough) behaviour

**Comment by ShezHsky** [comment]
Fixed by #228
